### PR TITLE
prevent hanging on Windows

### PR DESCRIPTION
**Pull request by chorny**

### CODE REVIEW

**Comment by plicease** [comment]
1.06 is already a prereq for PlugAuth.

**Comment by plicease** [comment]
Is it possible you were testing a version prior to 0.32?

**Comment by chorny** [comment]
My smoker has a previous version of Clustericious installed. When testing PlugAuth, CPAN.pm tries to build Clustericious 1.06, but it fails. Because requirement of 1.06 is specified only in Makefile.PL, previous version of Clustericious is used. And tests hang with this version. With release of Clustericious 1.07, problem will not manifest, but it may appear if future version of Clustericious will fail tests.

**Comment by plicease** [comment]
Forgive if I am missing something, but I don't think CPAN.pm should attempt to test/install if the prerequisites aren't met.

**Comment by chorny** [comment]
Such behavior of CPAN.pm has some advantages - some authors set prerequisites for latest versions without any reason, so when latest version fails it is not possible to install module. So CPAN.pm still runs tests to check if module can work.

**Comment by plicease** [comment]
Some authors also set prerequisites for a particular version because they don't want to support older versions, as is the case here.

I'm not happy putting the version declaration in lib/PlugAuth/Client.pm ... that file hasn't changed in some time and putting it in there would suggest that file in particular requires that version, which is misleading.

Can you tell me what version of Clustericious was installed, and which test hung?

**Comment by chorny** [comment]
> Some authors also set prerequisites for a particular version because they don't want to support older versions

I usually just make version requirement higher if problem appears with older version.

> I'm not happy putting the version declaration in lib/PlugAuth/Client.pm

I can always block it on my smoker if this problems appears again.

> Can you tell me what version of Clustericious was installed, and which test hung?

0.9945
11-client.t

**Comment by plicease** [comment]
I appreciate the report because I value cpan testers and I like to keep the smokers even on Windows happy, and PR where things are obvious are good too, but please also provide be with enough detail to reproduce, in case your fix isn't appropriate:

 - using the version declaration in `PlugAuth/Client.pm` was not appropriate since that file does not actually require that version
 - declaring a required version in a use statement at all is problematic for me since I am frequently testing against a `Clustericious` which is checked out of git and doesn't have versions.

I tested with the above commit on `0.9945` and it no longer hangs for me.  I also tested against all versions since and including 1.00 and they do not hang either.

**Pull request closed without merging**
